MusicTribe/MusicTribe/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('homepage/', include('app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('USER/',include('django.contrib.auth.urls')),
]

MusicTribe/accounts/urls.py
from django.urls import path
from . import views
from app.views import index

app_name = 'accounts'
urlpatterns =[
    path('', index, name='index'),
    path('signup/', views.signup_view, name="signup"),
    path('EDIT_USER/<member_id>',views.EditUserView,name='edit-user'),
    path('EDIT_USER/password',views.UpdatePasswordView,name='update-password'),
    path('ADD_ADMIN/<member_id>',views.createAdmin,name='create-admin'),
    path('ADD_SUPER_ADMIN/<member_id>',views.createSuperAdmin,name='create-super-admin'),
    ]

MusicTribe/app/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import create_tribe,create_playlist,create_song,update_song,update_playlist,update_tribe,create_comment,update_comment
from django.conf import settings
from django.conf.urls.static import static

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('tribe/<int:tribe_id>',views.tribeview,name='tribe-view'),
    path('tribe/<int:tribe_id>/playlist/<int:playlist_id>',views.playlistview,name='playlist-view'),
    path('new_tribe', login_required(create_tribe.as_view()), name="new-tribe"),
    path('update_tribe/<pk>', update_tribe.as_view(), name="update-tribe"),
    path('delete_tribe/<tribe_id>', views.delete_tribe, name="delete-tribe"),
    path('<int:tribe_id>/new_playlist/', login_required(create_playlist.as_view()), name="create-playlist"),
    path('update_playlist/<int:tribe_id>/<pk>', update_playlist.as_view(), name="update-playlist"),
    path('delete_playlist/<int:playlist_id>/', views.delete_playlist, name="delete-playlist"),
    path('<int:tribe_id>/<int:playlist_id>/new_song', login_required(create_song.as_view()), name="create-song"),
    path('update_song/<int:playlist_id><pk>', update_song.as_view(), name="update-song"),
    path('delete_song/<song_id>',views.delete_song, name="delete-song"),
    path('<int:song_id>/upvote', views.upvote, name='upvote'),
    path('tribe/<int:tribe_id>/join',views.join_tribe,name='join-tribe'),
    path('commentview', views.commentview,name='commentview'),
    path('commenterview', views.commenterview,name='commenterview'),
    path('update_comment/<int:song_id>/<pk>', update_comment.as_view(), name='update-comment'),
    path('create_comment/<int:song_id>', login_required(create_comment.as_view()), name='create-comment'),
    path('delete_comment/<int:song_id>/<int:comment_id>', views.delete_comment, name='delete-comment'),
    path('search_users',views.search_users,name='search-users'),
]

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

MusicTribe/app/templates/app/base.html
{% load static %}
{% load app_extras %}
<html>
<head>
    <title>Music Tribe</title>


    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" crossorigin="anonymous" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" crossorigin="anonymous" integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" crossorigin="anonymous" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" crossorigin="anonymous" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"></script>

    {% block extrahead %}
    {% endblock %}

    <link rel="stylesheet" href="{%  static 'app/css/musictribe.css' %}">

    <style>
        .Fixed {
            position: fixed;
            bottom: 20px;
            right: -20px;
        }


        aside {
            float: right;
            margin: 0 1.5%;
            width: 30%;
            margin-top: 50px;
            z-index: 1;
        }

        .popup {
            position: relative;
            display: inline-block;
            cursor: pointer;
        }

            /* The actual popup (appears on top) */
            .popup .popuptext {
                display: none;
                width: 500px;
                background-color: bisque;
                color: black;
                text-align: center;
                border-radius: 6px;
                padding: 8px 0;
                position: absolute;
                z-index: 1;
                top: 125%;
                left: 50%;
                margin-left: -80px;
            }

                /* Popup arrow */
                .popup .popuptext::after {
                    content: "";
                    position: absolute;
                    bottom: 100%;
                    left: 50%;
                    margin-left: -5px;
                    border-width: 5px;
                    border-style: solid;
                    border-color: #555 transparent transparent transparent;
                }

            /* Toggle this class when clicking on the popup container (hide and show the popup) */
            .popup .show {
                display: block;
                -webkit-animation: fadeIn 1s;
                animation: fadeIn 1s
            }

        /* Add animation (fade in the popup) */
        @-webkit-keyframes fadeIn {
            from {
                opacity: 0;
            }

            to {
                opacity: 1;
            }
        }

        @keyframes fadeIn {
            from {
                opacity: 0;
            }

            to {
                opacity: 1;
            }
        }
    </style>
</head>
<body>
    <div class="page-header">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'app:index'%}">MusicTribe</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                </ul>

                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                    <img class="profile-image" src="/homepage{{request.user.member.profile_pic.url}}" width="35px" height="35px" style="border-radius:50%;"></img>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'accounts:edit-user' user.member.id%}">Hi {{ user.username }}! </a>
                    </li>

                    {% if user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link" href="/admin">Admin dashboard</a>
                    </li>
                    {% elif request.user|has_group:"admin" %}
                    <li class="nav-item">
                        <a class="nav-link" href="/admin">Admin dashboard</a>
                    </li>
                    {% endif %}

                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'logout' %}">Logout </a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'login' %}">Login </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:signup' %}">Signup </a>
                    </li>
                    {% endif %}
                </ul>

            </div>
        </nav>

    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-12">
                <div class="jumbotron fluid-jumbotron">
                    <div class="container">
                        <h1 class="display-4">MusicTribe</h1>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

MusicTribe/app/templates/app/create_comment.html
{%extends 'app/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h2 class="text-center">{{action.name}}</h2><br>
    </div>
</div>
<form method="post" accept-charset="utf-8">
    {% csrf_token %}
    {% include 'includes/bs4_form.html' with form=form %}
    <div class="row">
        <div class="col-md-8 mx-auto">
            <input type="submit" value="{{action.value}}" class="btn btn-primary" />
        </div>
    </div>
</form>
{% endblock content %}

MusicTribe/app/templates/app/create_playlist.html
{%extends 'app/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h2 class="text-center">{{action.name}}</h2><br>
    </div>
</div>
<form method="post" accept-charset="utf-8">
    {% csrf_token %}
    {% include 'includes/bs4_form.html' with form=form %}
    <div class="row">
        <div class="col-md-8 mx-auto">
            <input type="submit" value="{{action.value}}" class="btn btn-primary" />
        </div>
    </div>
</form>
{% endblock content %}

MusicTribe/app/templates/app/create_song.html
{%extends 'app/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h2 class="text-center">{{action.name}}</h2><br>
    </div>
</div>
<form method="post" accept-charset="utf-8">
    {% csrf_token %}
    {% include 'includes/bs4_form.html' with form=form %}
    <div class="row">
        <div class="col-md-8 mx-auto">
            <input type="submit" value="{{action.value}}" class="btn btn-primary" />
        </div>
    </div>
</form>
{% endblock content %}

MusicTribe/app/templates/app/create_tribe.html
{%extends 'app/base.html' %}

{% block content %}

<style>
    ul{
        align-self:center;
    }
    li {
        list-style-type: none;
    }
</style>
<div class="row">
    <div class="col-md-12">
        <h2 class="text-center">{{action.name}}</h2><br>
    </div>
</div>
<form method="post" accept-charset="utf-8">
    {% csrf_token %}
    {% include 'includes/bs4_form.html' with form=form %}
    <div class="row">
        <div class="col-md-8 mx-auto">
            <input type="submit" value="{{action.value}}" class="btn btn-primary" />
        </div>
    </div>
</form>
{% endblock content %}

MusicTribe/app/templates/app/homepage.html
{% extends 'app/base.html' %}


{% block content %}
<body>
    {% if user.is_staff %}
    <form class="d-flex" method="post" action="{% url 'app:search-users' %}">
        {% csrf_token %}

        <input name="user" class="form-control me-2" type="search" placeholder="Search users" arial-label="Search users">
        <button type="submit">
            Search
        </button>
    </form>
    {% endif %}

    {% if user.is_authenticated%}
    <div class="row">
        <div class="col-md-10">
            <p><a href="{% url 'app:new-tribe' %}">Create new tribe</a></p>
        </div>
    </div>
    {% endif %}


    <div class="row">
        <div class="col-md-10">

        </div>
    </div>
    {% if tribe_list %}
    {% for tribe in tribe_list %}
    <div class="row">
        <div class="col-md-2">

        </div>
        <div class="col-md-10">
            <h2><a href="{% url 'app:tribe-view' tribe.id %}">{{ tribe.name }}</a></h2>
        </div>
        <div class="date">
            <p class="black" style="margin-left:250px">
                Published: {{ tribe.created_at }}
            </p>
        </div>
    </div>
    <br />
    {% endfor %}
    {% endif %}
</body>
{% endblock %}

MusicTribe/app/templates/app/playlist.html
{% extends 'app/base.html' %}


{% block content %}


<div class="row">
    <div class="col-md-10">
        <h1>{{ playlist.name }} </h1>
        <p>{{playlist.description}}</p>
        {% if tribe.chieftain == user  %}
        <div class="col-md-2">
            <p><a href="{% url 'app:update-playlist' playlist.tribe.id playlist.id %}">Update playlist</a></p>
        </div>
        {% elif user.is_staff %}
        <div class="col-md-2">
            <p><a href="{% url 'app:update-playlist' playlist.tribe.id playlist.id %}">Update playlist</a></p>
        </div>
        {%endif%}

        {% if tribe.chieftain == user  %}
        <div class="col-md-2">
            <p><a href="{% url 'app:delete-playlist' playlist.id %}">Delete playlist</a></p>
        </div>
        {% elif user.is_staff %}
        <div class="col-md-2">
            <p><a href="{% url 'app:delete-playlist' playlist.id %}">Delete playlist</a></p>
        </div>
        {%endif%}
    </div>
</div>
<br />
<div>
    {% if user.member in tribe.tribe_members.all  %}
    <p><a href="{% url 'app:create-song' tribe.id playlist.id %}">Create new song</a></p>
    {% elif tribe.chieftain == user %}
    <p><a href="{% url 'app:create-song' tribe.id playlist.id %}">Create new song</a></p>
    {% elif user.is_staff %}
    <p><a href="{% url 'app:create-song' tribe.id playlist.id %}">Create new song</a></p>
    {%endif%}
</div>
{% if user.is_authenticated %}
    {% if user.member in tribe.tribe_members.all  %}
<aside class="Fixed">
    {% include "includes/tribe_chat_form.html" with room_id=room_id tribe=tribe %}
</aside>
    {% endif %}
{% endif %}

{% if songs %}

    {% for song,vote,comments in songs %}
        <div class="row">
            {% include "includes/song_form.html" with song=song vote=vote comments=comments%}
         </div>
        <br>
    {% endfor %}
{% endif %}

    {% block javascript %}
        <script>

            function myFunction(id) {
                var popup = document.getElementById("myPopup" + id);
                    popup.classList.toggle("show");
            }

    </script>
    {% endblock javascript %}
{% endblock %}

MusicTribe/app/templates/app/tribe.html
{% extends 'app/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-10">
        <h1>{{ tribe.name }}</h1>
        {% if tribe.chieftain == user %}
        <div class="col-md-2">
            <p><a href="{% url 'app:update-tribe' tribe.id %}">Update tribe</a></p>
        </div>
        <div class="col-md-10"></div>
        {% elif user.is_staff %}
        <div class="col-md-2">
            <p><a href="{% url 'app:update-tribe' tribe.id %}">Update tribe</a></p>
        </div>
        <div class="col-md-10"></div>
        {%endif%}

        {% if tribe.chieftain == user %}
        <div class="col-md-2">
            <p><a href="{% url 'app:delete-tribe' tribe.id %}">Delete tribe</a></p>
        </div>
        <div class="col-md-10"></div>
        {% elif user.is_staff %}
        <div class="col-md-2">
            <p><a href="{% url 'app:delete-tribe' tribe.id %}">Delete tribe</a></p>
        </div>
        <div class="col-md-10"></div>
        {%endif%}
    </div>
</div>
<br />
<div>
    {% if user.member in tribe.tribe_members.all  %}
    <p><a href="{% url 'app:create-playlist' tribe.id %}">Create new playlist</a></p>
    {% elif tribe.chieftain == user %}
    <p><a href="{% url 'app:create-playlist' tribe.id %}">Create new playlist</a></p>
    {%endif%}
</div>
<br />
{% if user.is_authenticated %}
    {% if user.member in tribe.tribe_members.all  %}
            
    {% else %}
    <div class="row">
        <div class="col-md-10">
            <p><a href="{% url 'app:join-tribe' tribe.id %}">Join tribe</a></p>
        </div>
    </div>
    {% endif %}
{% endif %}

{% if user.is_authenticated %}
    {% if user.member in tribe.tribe_members.all  %}
        <aside class="Fixed">
            {% include "includes/tribe_chat_form.html" with room_id=room_id tribe=tribe %}
        </aside>
    {% elif user.is_staff  %}
         <aside class="Fixed">
            {% include "includes/tribe_chat_form.html" with room_id=room_id tribe=tribe %}
        </aside>
    {% endif %}
{% endif %}

{% if playlists %}
    {% for playlist in playlists %}
<div class="row" style="z-index:-1">
    <div class="col-md-10">
        <div class="date">
            <p class="red">
                Created: {{ playlist.created_at }}
            </p>
        </div>
        <h2><a href="{% url 'app:playlist-view' tribe.id playlist.id %}">{{ playlist.name }}</a></h2>
        <p>{{ playlist.description }}</p>
        {% if tribe.chieftain == user %}
        <p><a href="{% url 'app:update-playlist' tribe.id playlist.id %}">Update playlist</a></p>
        {% elif user.is_staff %}
        <p><a href="{% url 'app:update-playlist' tribe.id playlist.id %}">Update playlist</a></p>
        {%endif%}

        {% if tribe.chieftain == user %}
        <p><a href="{% url 'app:delete-playlist' playlist.id %}">Delete playlist</a></p>
        {% elif user.is_staff %}
        <p><a href="{% url 'app:delete-playlist' playlist.id %}">Delete playlist</a></p>
        {%endif%}
        <hr />
    </div>
    <div class="col-md-2">

    </div>
</div>


    {% endfor %}
{% endif %}



{% endblock %}

MusicTribe/app/templates/app/user_search.html
{%extends 'app/base.html' %}

{% block content %}
<div>
	{% if user_list %}
	{%for users in user_list%}
	<a href="{%url 'accounts:edit-user' users.id%}">{{users}}</a>
	<br>
	{%endfor%}
	{%else%}
	<h3> Please enter a username for searching</h3>
	{%endif%}
</div>

{%endblock%}