MusicTribe/MusicTribe/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('homepage/', include('app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('USER/',include('django.contrib.auth.urls')),
]

MusicTribe/app/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import create_tribe,create_playlist,create_song,update_song,update_playlist,update_tribe,create_comment,update_comment
from django.conf import settings
from django.conf.urls.static import static

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('tribe/<int:tribe_id>',views.tribeview,name='tribe-view'),
    path('tribe/<int:tribe_id>/playlist/<int:playlist_id>',views.playlistview,name='playlist-view'),
    path('new_tribe', login_required(create_tribe.as_view()), name="new-tribe"),
    path('update_tribe/<pk>', update_tribe.as_view(), name="update-tribe"),
    path('delete_tribe/<tribe_id>', views.delete_tribe, name="delete-tribe"),
    path('<int:tribe_id>/new_playlist/', login_required(create_playlist.as_view()), name="create-playlist"),
    path('update_playlist/<int:tribe_id>/<pk>', update_playlist.as_view(), name="update-playlist"),
    path('delete_playlist/<int:playlist_id>/', views.delete_playlist, name="delete-playlist"),
    path('<int:tribe_id>/<int:playlist_id>/new_song', login_required(create_song.as_view()), name="create-song"),
    path('update_song/<int:playlist_id><pk>', update_song.as_view(), name="update-song"),
    path('delete_song/<song_id>',views.delete_song, name="delete-song"),
    path('<int:song_id>/upvote', views.upvote, name='upvote'),
    path('tribe/<int:tribe_id>/join',views.join_tribe,name='join-tribe'),
    path('commentview', views.commentview,name='commentview'),
    path('commenterview', views.commenterview,name='commenterview'),
    path('update_comment/<int:song_id>/<pk>', update_comment.as_view(), name='update-comment'),
    path('create_comment/<int:song_id>', login_required(create_comment.as_view()), name='create-comment'),
    path('delete_comment/<int:song_id>/<int:comment_id>', views.delete_comment, name='delete-comment'),
    path('search_users',views.search_users,name='search-users'),
]

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

MusicTribe/tribe_chat/models.py
from django.db import models
from django.conf import settings
from app.models import Tribe

class TribeChatRoom(models.Model):

	# Room title
	title 				= models.CharField(max_length=255, unique=True, blank=False,)

	# all users who are authenticated and viewing the chat
	users 				= models.ManyToManyField(settings.AUTH_USER_MODEL, help_text="users who are connected to chat room.", blank=True)

	tribe				=models.OneToOneField(Tribe,on_delete=models.CASCADE)

	def __str__(self):
		return self.title


	def connect_user(self, user):
		is_user_added = False
		if not user in self.users.all():
			self.users.add(user)
			self.save()
			is_user_added = True
		elif user in self.users.all():
			is_user_added = True
		return is_user_added 


	def disconnect_user(self, user):
		is_user_removed = False
		if user in self.users.all():
			self.users.remove(user)
			self.save()
			is_user_removed = True
		return is_user_removed 


	@property
	def group_name(self):
		return "TribeChatRoom-%s" % self.id


class TribeRoomChatMessageManager(models.Manager):
    def by_room(self, room):
        qs = TribeRoomChatMessage.objects.filter(room=room).order_by("-timestamp")
        return qs

class TribeRoomChatMessage(models.Model):
    """
    Chat message created by a user inside a TribeChatRoom
    """
    user                = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    room                = models.ForeignKey(TribeChatRoom, on_delete=models.CASCADE)
    timestamp           = models.DateTimeField(auto_now_add=True)
    content             = models.TextField(unique=False, blank=False,)

    objects = TribeRoomChatMessageManager()

    def __str__(self):
        return self.content


MusicTribe/tribe_chat/views.py
from django.shortcuts import render

# Create your views here.

MusicTribe/app/templates/includes/bs4_form.html
{% block content %}
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
{{ hidden_field }}
{% endfor %}
	{% if form.non_field_errors %}
<div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
    {{ error }}
    {% endfor %}
</div>
	{% endif %}
{% for field in form.visible_fields %}
<div class="row form-group">
    <div class="col-md-8 controls mx-auto" style="padding:5px">
        {{ field.label_tag }}
        {% if form.is_bound %}
        {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
        <div class="invalid-feedback">
            {{ error }}
        </div>
        {% endfor %}
        {% else %}
        {%render_field field class="form-control is-valid" %}
        {% endif %}
        {% else %}
        {% render_field field class="form-control" %}
        {% endif %}
        {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
    </div>
</div>
{% endfor %}
{% endblock content %}

MusicTribe/app/templates/includes/comment_form.html
{% block content %}
{% for comment in comments %}
<br>
<div style="border:solid; border-width:thin; border-color:cornflowerblue;">
    <h5>{{comment.member.username}}</h5>
    <p class="red">
        {{ playlist.created_at}}
    </p>
    <div style="border-top:solid;border-bottom:solid; border-width:thin; border-color:cornflowerblue;">
        <p>{{comment.text}}</p>
    </div>
    {%  if user.is_staff %}
    <a href="{%url 'app:update-comment' song.id comment.id %}">Edit</a>
    {%  elif comment.member.user == user %}
    <a href="{%url 'app:update-comment' song.id comment.id %}">Edit</a>
    {%  endif %}

    {%  if user.is_staff %}
    <a href="{%url 'app:delete-comment' song.id comment.id %}">Delete</a>
    {%  elif comment.member.user == user %}
    <a href="{%url 'app:delete-comment' song.id comment.id %}">Delete</a>
    {%  endif %}
</div>
{% endfor %}
{% endblock content %}

MusicTribe/app/templates/includes/song_form.html
{% block content %}
<head>
    <style>
        .commentbox {
            border-style: solid;
            border-color: indianred;
        }
    </style>
</head>
    <div class="col-md-2">
    </div>
    <div class="col-md-10">
        <div>
            {% include "includes/vote_buttons.html" with song=song vote=vote %}
        </div>
        <div class="date">
            <p class="red">
                Created: {{ song.created_at }}
            </p>
        </div>
        <iframe width="420" height="315" src="{{ song.get_url}}"></iframe>
        <h3>Song:   {{song.track_name}}</h3>
        <div style="padding-left:20px; padding-bottom:5px;">
            <p>ARTIST:{{ song.track_artist|linebreaksbr }}</p>
            <p>DURATION:   {{song.duration}}</p>
            {%  if song.member.user == user  %}
            <p><a href="{% url 'app:update-song' playlist.id song.id %}">Update song</a></p>
            <p><a href="{% url 'app:delete-song' song.id %}">Delete song</a></p>
            {% elif user.is_staff %}
            <p><a href="{% url 'app:update-song' playlist.id song.id %}">Update tribe</a></p>
            <p><a href="{% url 'app:delete-song' song.id %}">Delete song</a></p>
            {%  endif   %}
            <div class="popup commentbox" id="{{song.id}}" onclick="myFunction({{song.id}})" style="text-align:center;">
                Comments <br /> {{song.comments.count}}
                <span class="popuptext " id="myPopup{{song.id}}">

                    {% if comments %}
                    {% include "includes/comment_form.html" with comments=comments%}
                    {% endif %}
                    <br>
                    {% if user.is_authenticated %}
                    <a href="{%url 'app:create-comment' song.id %}">Comment</a>
                    <br>
                    {%endif%}
                </span>
            </div>
        </div>
    </div>
<br />
<br />
{% endblock content %}

MusicTribe/app/templates/includes/tribe_chat_form.html
{% block content %}
<style type="text/css">

    .chat-log {
        height: 500px;
        overflow-x: hidden;
        overflow-y: auto;
        padding: 10px;
        background-color: #fff;
        font-size: 0.9em;
        flex-direction: column-reverse;
    }

    .profile-image {
        width: 33px;
        height: 33px;
        margin-top: 0px;
        margin-bottom: auto;
    }

    .timestamp-span {
        font-weight: 400;
        font-size: 0.8em;
        color: var(--secondary-text-color);
    }


    #id_chatroom_loading_spinner {
        position: absolute;
    }


    .connected-users {
        color: red;
    }

    .connected-users-icon {
        color: red;
    }

        .connected-users-icon:hover {
            cursor: default;
        }

</style>

{% if debug %}
TRIBE CHAT
{% endif %}
<span class="{% if not debug %}d-none{% endif %} page-number" id="id_page_number">1</span>

<div class="card ml-3">

	<div class="card-header">
		<div class="d-flex flex-row justify-content-between">
			<h3 class="">{{tribe}} Chat</h3>
			<div class="d-flex flex-row align-items-center">
				<span class="material-icons m-auto pr-1 connected-users-icon" style="display:none;">Connected users:</span>
				<span class="m-auto connected-users"style="display:none;" id="id_connected_users"></span>
			</div>
		</div>
	</div>
	<div class="card-body p-1">
		<div class="d-flex flex-column" id="id_chat_log_container">
			<div class="d-flex flex-row justify-content-center" id="id_chatroom_loading_spinner_container">
				<div class="spinner-border text-primary" id="id_chatroom_loading_spinner" role="status" style="display: none; ">
					<span class="sr-only">Loading...</span>
				</div>
			</div>
			<div class="d-flex chat-log" id="id_chat_log">

			</div>
			<div class="d-flex chat-message-input-container">
				<textarea class="flex-grow-1 chat-message-input" id="id_chat_message_input"></textarea>
				<button class="btn btn-primary chat-message-submit-button">
					<span id="id_chat_message_submit" class="material-icons">
						send
					</span>
				</button>
			</div>
		</div>
	</div>
</div>


<script type="text/javascript">
		var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
		{% if debug_mode %}
			var ws_path = ws_scheme + '://' + window.location.host + "/homepage/tribe/{{tribe.id}}/"; 
		{% else %}
        var ws_path = ws_scheme + '://' + window.location.host + ":8001/homepage/tribe/{{tribe.id}}/";
		{% endif %}
		var tribe_chat_socket = new WebSocket(ws_path);

				// Handle incoming messages
		tribe_chat_socket.onmessage = function(message) {
			console.log("Got chat websocket message " + message.data);
			var data = JSON.parse(message.data);

            displayChatroomLoadingSpinner(data.display_progress_bar)

            if (data.error) {
                console.error(data.error + ": " + data.message)
                showClientErrorModal(data.message)
                return;
            }

			if (data.join) {
					console.log("Joining tribe room " + data.join);
					getRoomChatMessages()
			}

			// Handle getting a message
			if (data.msg_type == 0) {
					appendChatMessage(data)
			}

            if (data.msg_type == 1) {
                setConnectedUsersCount(data['connected_user_count'])
            }

			if (data.messages_payload) {
				console.log("PAYLOAD")
				handleMessagesPayload(data.messages, data.new_page_number)
			}
			
		};

		tribe_chat_socket.addEventListener("open", function (e) {
            console.log("Tribe ChatSocket OPEN")
            // join chat room
            if ("{{request.user.is_authenticated}}") {
                tribe_chat_socket.send(JSON.stringify({
                    "command": "join",
                    "room": "{{room_id}}"
                }));
            }
        })





		tribe_chat_socket.onclose = function(e) {
			console.error('Tribe ChatSocket closed.');
		};
		tribe_chat_socket.onOpen = function(e){
			console.log("Tribe ChatSocket onOpen", e)
		}
		tribe_chat_socket.onerror = function(e){
	        console.log('Tribe ChatSocket error', e)
	    }
	    if (tribe_chat_socket.readyState == WebSocket.OPEN) {
	    	console.log("Tribe ChatSocket OPEN")
	    } else if (tribe_chat_socket.readyState == WebSocket.CONNECTING){
	        console.log("Tribe ChatSocket connecting..")
	    }

		document.getElementById('id_chat_message_input').focus();
		document.getElementById('id_chat_message_input').onkeyup = function(e) {
			if (e.keyCode === 13 && e.shiftKey) {  // enter + return
				// Handled automatically by textarea
			}
			else if(e.keyCode === 13 && !e.shiftKey){ // enter + !return
				document.getElementById('id_chat_message_submit').click();
			}
		};

	    document.getElementById('id_chat_message_submit').onclick = function(e) {
			const messageInputDom = document.getElementById('id_chat_message_input');
			const message = messageInputDom.value;
			tribe_chat_socket.send(JSON.stringify({
				"command": "send",
                "message": message,
                "room_id": "{{room_id}}"
			}));
			messageInputDom.value = '';
		};

	function appendChatMessage(data,payload) {
		message = data['message']
		uName = data['username']
		user_id = data['user_id']
		profile_image = data['profile_image']
        timestamp = data['natural_timestamp']

		var msg = message + '\n';
		var username = uName + ": "
		var pay = payload
        createChatMessageElement(pay,msg, username, profile_image, user_id, timestamp)
	}

    function handleMessagesPayload(messages, new_page_number) {
        if (messages != null && messages != "undefined" && messages != "None") {
            setPageNumber(new_page_number)
            messages.forEach(function (message) {
                appendChatMessage(message,true, true, false)
            })
        }
        else {
            setPaginationExhausted() // no more messages
        }
    }

    function setPageNumber(pageNumber) {
        document.getElementById("id_page_number").innerHTML = pageNumber
    }

    function setPaginationExhausted() {
        setPageNumber("-1")
    }

    /*
        Retrieve the chat room messages given the page number.
    */
    function getRoomChatMessages() {
        var pageNumber = document.getElementById("id_page_number").innerHTML
        if (pageNumber != "-1") {
            setPageNumber("-1") // Do not allow any other queries while one is in progress
            tribe_chat_socket.send(JSON.stringify({
                "command": "get_room_chat_messages",
                "room_id": "{{room_id}}",
                "page_number": pageNumber,
            }));
        }
    }

    /*
        Get the next page of chat messages when scrolls to bottom
    */
    document.getElementById("id_chat_log").addEventListener("scroll", function (e) {
        var chatLog = document.getElementById("id_chat_log")
        chatLog.addEventListener("scroll", function (e) {
            if ((Math.abs(chatLog.scrollTop) + 2) >= (chatLog.scrollHeight - chatLog.offsetHeight)) {
                getRoomChatMessages()
            }
        });
    })

	function createChatMessageElement(payload,msg, username, profile_image, user_id, timestamp) {
		var chatLog = document.getElementById("id_chat_log")

		var newMessageDiv = document.createElement("div")
		newMessageDiv.classList.add("d-flex")
		newMessageDiv.classList.add("flex-row")

		var profileImage = document.createElement("img")
		profileImage.classList.add("profile-image")
		profileImage.classList.add("rounded-circle")
		profileImage.classList.add("img-fluid")
		profileImage.src = profile_image
		newMessageDiv.appendChild(profileImage)

		var div1 = document.createElement("div")
		div1.classList.add("d-flex")
		div1.classList.add("flex-column")

		var div2 = document.createElement("div")
		div2.classList.add("d-flex")
		div2.classList.add("flex-row")

		var usernameSpan = document.createElement("span")
		usernameSpan.innerHTML = username
		div2.appendChild(usernameSpan)

        var timestampSpan = document.createElement("span")
        timestampSpan.innerHTML = timestamp
        timestampSpan.classList.add("timestamp-span")
        timestampSpan.classList.add("d-flex")
        timestampSpan.classList.add("align-items-center")
        timestampSpan.addEventListener("click", function (e) {
            selectUser(user_id)
        })
        div2.appendChild(timestampSpan)

		div1.appendChild(div2)

		var msgP = document.createElement("p")
		msgP.innerHTML = msg
		msgP.classList.add("msg-p")
		div1.appendChild(msgP)

		newMessageDiv.appendChild(div1)

		if (payload) {
			chatLog.insertBefore(newMessageDiv, chatLog.lastchild)
		} else (
			chatLog.insertBefore(newMessageDiv, chatLog.firstChild.nextSibling)
			)
	}

    function showClientErrorModal(message) {
        document.getElementById("id_client_error_modal_body").innerHTML = message
        document.getElementById("id_trigger_client_error_modal").click()
    }

    function displayChatroomLoadingSpinner(isDisplayed) {
        var spinner = document.getElementById("id_chatroom_loading_spinner")
		if (isDisplayed) {
			spinner.style.display = "block"
        }
        else {
            spinner.style.display = "none"
        }
	}

    function setConnectedUsersCount(count) {
        element = document.getElementById("id_connected_users")
        element.innerHTML = count
    }
</script>

<button type="button" id="id_trigger_client_error_modal" class="d-none btn btn-primary" data-toggle="modal" data-target="#id_client_error_modal">
</button>
<div class="modal fade" id="id_client_error_modal" tabindex="-1" role="dialog">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Socket Client Error</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<p id="id_client_error_modal_body">Something went wrong.</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal" id="id_client_error_modal_close_btn">Close</button>
			</div>
		</div>
	</div>
</div>
<!-- Client Error MODAL -->
{% endblock content %}

MusicTribe/app/templates/includes/vote_buttons.html
{% block content %}
<div>
    <form action="{% url 'app:upvote' song.id %}"
          method="post"
          role="form"
          class="form-inline float-left">
        {% csrf_token %}
        <input type="submit" value="Upvote" class="btn {{vote.upvote|yesno:'btn-success,'}}" />
    </form>

    <span class="vote-score float-left">{{ song.vote_score}}</span>
</div>
{% endblock content %}